<!DOCTYPE html>

<html lang="en">
<head>
     <meta charset="utf-8" />
     <title>Welcome to BMWLand</title>
     <link rel="stylesheet" type="text/css" href="projectstyle.css">
     <style>
     	#map-canvas {
        width: 500px;
        height: 400px;
        }

        body { background: url(755102-bmw-wallpaper.jpg) no-repeat center center fixed; background-size: center; background-repeat: no-repeat; font-family: helvetica;}

     </style>
</head>
<body>


	<legend>BMW Models</legend>
		
		<!-- Start cssSlider.com -->
		<!-- Generated by cssSlider.com 2.0 -->
		<link rel="stylesheet" href="cssslider_files/csss_engine1/style.css">
		<!--[if IE]><link rel="stylesheet" href="cssslider_files/csss_engine1/ie.css"><![endif]-->
		<!--[if lte IE 9]><script type="text/javascript" src="cssslider_files/csss_engine1/ie.js"></script><![endif]-->
		 <div class="csslider1 autoplay ">
		<input name="cs_anchor1" id="cs_slide1_0" type="radio" class="cs_anchor slide">
		<input name="cs_anchor1" id="cs_slide1_1" type="radio" class="cs_anchor slide">
		<input name="cs_anchor1" id="cs_slide1_2" type="radio" class="cs_anchor slide">
		<input name="cs_anchor1" id="cs_slide1_3" type="radio" class="cs_anchor slide">
		<input name="cs_anchor1" id="cs_slide1_4" type="radio" class="cs_anchor slide">
		<input name="cs_anchor1" id="cs_slide1_5" type="radio" class="cs_anchor slide">
		<input name="cs_anchor1" id="cs_slide1_6" type="radio" class="cs_anchor slide">
		<input name="cs_anchor1" id="cs_slide1_7" type="radio" class="cs_anchor slide">
		<input name="cs_anchor1" id="cs_play1" type="radio" class="cs_anchor" checked="">
		<input name="cs_anchor1" id="cs_pause1_0" type="radio" class="cs_anchor pause">
		<input name="cs_anchor1" id="cs_pause1_1" type="radio" class="cs_anchor pause">
		<input name="cs_anchor1" id="cs_pause1_2" type="radio" class="cs_anchor pause">
		<input name="cs_anchor1" id="cs_pause1_3" type="radio" class="cs_anchor pause">
		<input name="cs_anchor1" id="cs_pause1_4" type="radio" class="cs_anchor pause">
		<input name="cs_anchor1" id="cs_pause1_5" type="radio" class="cs_anchor pause">
		<input name="cs_anchor1" id="cs_pause1_6" type="radio" class="cs_anchor pause">
		<input name="cs_anchor1" id="cs_pause1_7" type="radio" class="cs_anchor pause">
		<ul>
			<li class="cs_skeleton"><img src="cssslider_files/csss_images1/bmw1series2013.jpg" style="width: 100%;"></li>
			<li class="num0 img slide"> <img src="cssslider_files/csss_images1/bmw1series2013.jpg" alt="1 Series" title="1 Series"></li>
			<li class="num1 img slide"> <img src="cssslider_files/csss_images1/2014bmwm235icoupeplacementnew626x382.jpg" alt="2 Series" title="2 Series"></li>
			<li class="num2 img slide"> <img src="cssslider_files/csss_images1/125x85xii_15582_1342178922088.jpg.pagespeed.ic.qv44aeelp5.jpg" alt="3 Series" title="3 Series"></li>
			<li class="num3 img slide"> <img src="cssslider_files/csss_images1/bmw4seriesactivehybrid.jpg" alt="4 Series" title="4 Series"></li>
			<li class="num4 img slide"> <img src="cssslider_files/csss_images1/carscoop_bmw_5_2007_0.jpg" alt="5 Series" title="5 Series"></li>
			<li class="num5 img slide"> <img src="cssslider_files/csss_images1/bmw6seriesgrancoupexl.jpg" alt="6 Series" title="6 Series"></li>
			<li class="num6 img slide"> <img src="cssslider_files/csss_images1/bmw_7series_teaser_com_bg.jpg" alt="7 Series" title="7 Series"></li>
			<li class="num7 img slide"> <img src="cssslider_files/csss_images1/visions03.jpg" alt="i8" title="i8"></li>
		</ul><div class="cs_engine"> </div>
		<div class="cs_description">
			<label class="num0"><span class="cs_title"><span class="cs_wrapper">1 Series</span></span></label>
			<label class="num1"><span class="cs_title"><span class="cs_wrapper">2 Series</span></span></label>
			<label class="num2"><span class="cs_title"><span class="cs_wrapper">3 Series</span></span></label>
			<label class="num3"><span class="cs_title"><span class="cs_wrapper">4 Series</span></span></label>
			<label class="num4"><span class="cs_title"><span class="cs_wrapper">5 Series</span></span></label>
			<label class="num5"><span class="cs_title"><span class="cs_wrapper">6 Series</span></span></label>
			<label class="num6"><span class="cs_title"><span class="cs_wrapper">7 Series</span></span></label>
			<label class="num7"><span class="cs_title"><span class="cs_wrapper">i8</span></span></label>
		</div>
		<div class="cs_play_pause">
			<label class="cs_play" for="cs_play1"><span><i></i><b></b></span></label>
			<label class="cs_pause num0" for="cs_pause1_0"><span><i></i><b></b></span></label>
			<label class="cs_pause num1" for="cs_pause1_1"><span><i></i><b></b></span></label>
			<label class="cs_pause num2" for="cs_pause1_2"><span><i></i><b></b></span></label>
			<label class="cs_pause num3" for="cs_pause1_3"><span><i></i><b></b></span></label>
			<label class="cs_pause num4" for="cs_pause1_4"><span><i></i><b></b></span></label>
			<label class="cs_pause num5" for="cs_pause1_5"><span><i></i><b></b></span></label>
			<label class="cs_pause num6" for="cs_pause1_6"><span><i></i><b></b></span></label>
			<label class="cs_pause num7" for="cs_pause1_7"><span><i></i><b></b></span></label>
			</div>
		<div class="cs_arrowprev">
			<label class="num0" for="cs_slide1_0"><span><i></i><b></b></span></label>
			<label class="num1" for="cs_slide1_1"><span><i></i><b></b></span></label>
			<label class="num2" for="cs_slide1_2"><span><i></i><b></b></span></label>
			<label class="num3" for="cs_slide1_3"><span><i></i><b></b></span></label>
			<label class="num4" for="cs_slide1_4"><span><i></i><b></b></span></label>
			<label class="num5" for="cs_slide1_5"><span><i></i><b></b></span></label>
			<label class="num6" for="cs_slide1_6"><span><i></i><b></b></span></label>
			<label class="num7" for="cs_slide1_7"><span><i></i><b></b></span></label>
		</div>
		<div class="cs_arrownext">
			<label class="num0" for="cs_slide1_0"><span><i></i><b></b></span></label>
			<label class="num1" for="cs_slide1_1"><span><i></i><b></b></span></label>
			<label class="num2" for="cs_slide1_2"><span><i></i><b></b></span></label>
			<label class="num3" for="cs_slide1_3"><span><i></i><b></b></span></label>
			<label class="num4" for="cs_slide1_4"><span><i></i><b></b></span></label>
			<label class="num5" for="cs_slide1_5"><span><i></i><b></b></span></label>
			<label class="num6" for="cs_slide1_6"><span><i></i><b></b></span></label>
			<label class="num7" for="cs_slide1_7"><span><i></i><b></b></span></label>
		</div>
		<div class="cs_bullets">
			<label class="num0" for="cs_slide1_0"> <span class="cs_point"></span>
				<span class="cs_thumb"><img src="cssslider_files/csss_tooltips1/bmw1series2013.jpg" alt="1 Series" title="1 Series"></span></label>
			<label class="num1" for="cs_slide1_1"> <span class="cs_point"></span>
				<span class="cs_thumb"><img src="cssslider_files/csss_tooltips1/2014bmwm235icoupeplacementnew626x382.jpg" alt="2 Series" title="2 Series"></span></label>
			<label class="num2" for="cs_slide1_2"> <span class="cs_point"></span>
				<span class="cs_thumb"><img src="cssslider_files/csss_tooltips1/125x85xii_15582_1342178922088.jpg.pagespeed.ic.qv44aeelp5.jpg" alt="3 Series" title="3 Series"></span></label>
			<label class="num3" for="cs_slide1_3"> <span class="cs_point"></span>
				<span class="cs_thumb"><img src="cssslider_files/csss_tooltips1/bmw4seriesactivehybrid.jpg" alt="4 Series" title="4 Series"></span></label>
			<label class="num4" for="cs_slide1_4"> <span class="cs_point"></span>
				<span class="cs_thumb"><img src="cssslider_files/csss_tooltips1/carscoop_bmw_5_2007_0.jpg" alt="5 Series" title="5 Series"></span></label>
			<label class="num5" for="cs_slide1_5"> <span class="cs_point"></span>
				<span class="cs_thumb"><img src="cssslider_files/csss_tooltips1/bmw6seriesgrancoupexl.jpg" alt="6 Series" title="6 Series"></span></label>
			<label class="num6" for="cs_slide1_6"> <span class="cs_point"></span>
				<span class="cs_thumb"><img src="cssslider_files/csss_tooltips1/bmw_7series_teaser_com_bg.jpg" alt="7 Series" title="7 Series"></span></label>
			<label class="num7" for="cs_slide1_7"> <span class="cs_point"></span>
				<span class="cs_thumb"><img src="cssslider_files/csss_tooltips1/visions03.jpg" alt="i8" title="i8"></span></label>
		</div>
		</div>
		<!-- End cssSlider.com -->
